[package]
name = "nom-supreme"
version = "0.4.1"
authors = ["Nathan West <Lucretiel@gmail.com>"]
edition = "2018"

readme = "README.md"
license = "MPL-2.0"
description = "A collection of excellent utilities for nom"
repository = "https://github.com/Lucretiel/nom-supreme"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cascade = "1.0.0"
indent_write = "2.0.0"
joinery = "2.0.0"
memchr = "2.3.4"
nom = "6.0.1"

[dev-dependencies]
cool_asserts = "1.0.3"
